//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefrigeratorApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public ProductType()
        {
            this.Products = new HashSet<Product>();
            this.Products_log = new HashSet<Products_log>();
        }
    
        public int ProductTypeId { get; set; }
        public string ProductName { get; set; }
        public string MesUnit { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Products_log> Products_log { get; set; }
    }
}
