//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefrigeratorApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public int ProductTypeId { get; set; }
        public double Quantity { get; set; }
        public System.DateTime AsOf { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
