USE [master]
GO

/****** Object:  Database [Refrigerator]    Script Date: 7/31/2023 11:13:30 AM ******/
CREATE DATABASE [Refrigerator]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Refrigerator', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLSERVER\MSSQL\DATA\Refrigerator.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Refrigerator_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLSERVER\MSSQL\DATA\Refrigerator_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Refrigerator].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Refrigerator] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Refrigerator] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Refrigerator] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Refrigerator] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Refrigerator] SET ARITHABORT OFF 
GO

ALTER DATABASE [Refrigerator] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Refrigerator] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Refrigerator] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Refrigerator] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Refrigerator] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Refrigerator] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Refrigerator] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Refrigerator] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Refrigerator] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Refrigerator] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Refrigerator] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Refrigerator] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Refrigerator] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Refrigerator] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Refrigerator] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Refrigerator] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Refrigerator] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Refrigerator] SET RECOVERY FULL 
GO

ALTER DATABASE [Refrigerator] SET  MULTI_USER 
GO

ALTER DATABASE [Refrigerator] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Refrigerator] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Refrigerator] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Refrigerator] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Refrigerator] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Refrigerator] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Refrigerator] SET  READ_WRITE 
GO

